### PR TITLE
Removed unix package upper bound and allowed hint dependency to float

### LINKED ISSUE #2: Unix depenency conflict
My current unix version is 2.7.0.0, which conflicts with testloop's requirements.

$ cabal install testloop
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: testloop-0.1.1.0 (user goal)
next goal: unix (dependency of testloop-0.1.1.0)
rejecting: unix-2.7.0.1/installed-23f..., 2.7.0.1, 2.7.0.0 (conflict: testloop
=> unix>=2.2.0.0 && <2.7)
rejecting: unix-2.6.0.1, 2.6.0.0 (conflict: base==4.7.0.0/installed-018...,
unix => base>=4.2 && <4.7)
rejecting: unix-2.5.1.1, 2.5.1.0 (conflict: base==4.7.0.0/installed-018...,
unix => base>=4.2 && <4.6)
rejecting: unix-2.5.0.0 (conflict: base==4.7.0.0/installed-018..., unix =>
base>=4.2 && <4.5)
rejecting: unix-2.4.2.0, 2.4.1.0 (conflict: base==4.7.0.0/installed-018...,
unix => base>=4.2 && <4.4)
rejecting: unix-2.4.0.2, 2.4.0.1 (conflict: base==4.7.0.0/installed-018...,
unix => base>=4.2 && <4.3)
rejecting: unix-2.4.0.0 (conflict: base==4.7.0.0/installed-018..., unix =>
base>=4.1 && <4.3)
trying: unix-2.3.2.0
next goal: hint (dependency of testloop-0.1.1.0)
rejecting: hint-0.4.1.0, 0.4.0.0 (conflict: testloop => hint==0.3.*)
trying: hint-0.3.3.7
next goal: ghc (dependency of hint-0.3.3.7)
rejecting: ghc-7.8.2/installed-a02... (conflict: unix==2.3.2.0, ghc =>
unix==2.7.0.1/installed-23f...)
Dependency tree exhaustively searched.

### PR DESCRIPTION
**Pull request by worrel**
Fixes issues using testloop with HaskellKoans on recent GHC on Ubuntu.  Resolves roman/testloop#2 and HaskVan/HaskellKoans#9

### CODE REVIEW

**Comment by Kazark** [comment]
@roman I'm still running into the issue described [here](https://github.com/HaskVan/HaskellKoans/issues/9). Could you merge this pull request?

**Comment by Kazark** [comment]
Awesome!

**Comment by ches** [comment]
It'd be great if you could push this release bump to Hackage and update the testloop dep in HaskellKoans, so it isn't broken out of the box. Chances are that folks wanting to try koans are new to Haskell, solving Cabal hell for themselves is not the finest early impression :grin:

**Comment by roman** [comment]
@ches thanks for the feedback, I'll try to have that fixed during the day.

Cheers.

**Comment by rafaqz** [comment]
We still have cabal hell ;) https://github.com/HaskVan/HaskellKoans/issues/10

Is there a reason your dependencies are generally so strict? It seems to work fine updating them.

**Pull request merged**
